---
name: "[Base] Lint Code Base"

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: sed -e 's/^#.*$//g' .github/super-linter.env | grep -v '^$' >> "$GITHUB_ENV"

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
