---
name: "[Base] Lint Code Base"

on:
  workflow_call:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          ENV=$(sed -e 's/^#.*$//g' .github/super-linter.env | grep -v '^$')
          echo "$ENV" >> "$GITHUB_ENV"

      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}
